Add documentation to the peoject
MiniTeks/mks-ui pull request #3
Opened 2022-02-12 17:24 UTC by avinal

- Add docs to the functions
- update readme

2022-02-13 05:50 UTC, RAMESSESII2 commented on README.md
> +This application needs a `go compiler` to build and a kubernetes cluster to run.
we should specify go 1.17 specifically!

2022-02-14 07:27 UTC, UtkarshChaurasia requested changes

2022-02-14 07:27 UTC, UtkarshChaurasia commented on cmd/web/handlers.go
> +		// log.Println(err.Error())
```suggestion
```
Remove the commented code

2022-02-14 11:07 UTC, UtkarshChaurasia approved these changes
lgtm

2022-02-14 11:08 UTC, merged